services:
  redis:
    image: redis:7.0.11
    ports:
      - "16379:6379"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  rstore:
    image: myyrakle/rstore:http-0.1.0
    container_name: rstore-http
    ports:
      - "13535:13535"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  rstore-tcp:
    image: myyrakle/rstore:tcp-0.1.0
    container_name: rstore-tcp
    ports:
      - "13536:13535"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M